variable "app_name" {
  type    = string
  default = "gostore"
}

variable "data_device" {
  description = "Block device holding persistent data (Postgres, and MinIO's if used), e.g. /dev/vdb on Vultr or /dev/sdb on Proxmox. Formatted ext4 and mounted at /mnt/gostore-data on first boot if it isn't already — never reformatted on a later apply, so resizing the disk in place doesn't lose data."
  type        = string
}

variable "container_image" {
  description = "Full image reference to run, e.g. ghcr.io/you/gostore:v1"
  type        = string
}

variable "base_url" {
  type = string
}

variable "domain" {
  description = "Public hostname Caddy requests a certificate for and serves on 443. Must match base_url's host."
  type        = string
}

variable "acme_email" {
  description = "Contact address for Let's Encrypt account registration and expiry notices."
  type        = string
}

variable "store_name" {
  type = string
}

variable "currency" {
  type    = string
  default = "ZAR"
}

variable "log_format" {
  description = "json everywhere here — LOG_FORMAT=gcp is for Cloud Logging's field names, which nothing on this stack reads."
  type        = string
  default     = "json"
}

# --- database (self-hosted Postgres, one container per environment) ---

variable "postgres_password" {
  type      = string
  sensitive = true
}

variable "postgres_data_mount" {
  description = "Host path bind-mounted into the postgres container. The caller formats and mounts the actual disk; this module only points compose at it."
  type        = string
  default     = "/mnt/gostore-data/postgres"
}

# --- setup token ---

variable "setup_token" {
  description = "Claims the first admin account at /admin/setup. Generated by the caller with random_password, not chosen by a human, same reasoning the GCP version used for its Secret Manager version."
  type        = string
  sensitive   = true
}

# --- payments ---

variable "payfast_sandbox" {
  description = "No default, on purpose — see the root modules' variables.tf for why."
  type        = bool
}

variable "payfast_merchant_id" {
  type      = string
  sensitive = true
}

variable "payfast_merchant_key" {
  type      = string
  sensitive = true
}

variable "payfast_passphrase" {
  type      = string
  sensitive = true
}

variable "snapscan_snap_code" {
  description = "Empty runs without SnapScan. There is no sandbox for it — see .env.example."
  type        = string
  default     = ""
}

variable "snapscan_api_key" {
  type      = string
  default   = ""
  sensitive = true
}

variable "snapscan_webhook_auth_key" {
  type      = string
  default   = ""
  sensitive = true
}

variable "snapscan_validation_key" {
  type      = string
  default   = ""
  sensitive = true
}

# --- mail ---

variable "smtp_host" {
  type = string
  validation {
    condition     = trimspace(var.smtp_host) != ""
    error_message = "smtp_host must not be empty — a store that cannot send receipts cannot deliver a digital download either."
  }
}

variable "smtp_port" {
  type    = number
  default = 587
}

variable "smtp_tls" {
  description = "starttls | tls | none"
  type        = string
  default     = "starttls"
}

variable "smtp_username" {
  type    = string
  default = ""
}

variable "smtp_password" {
  type      = string
  default   = ""
  sensitive = true
}

variable "email_from" {
  type = string
  validation {
    condition     = trimspace(var.email_from) != ""
    error_message = "email_from must not be empty — required together with smtp_host."
  }
}

variable "order_notify_email" {
  type    = string
  default = ""
}

# --- product images ---
#
# Two shapes, matching the two backends the server actually supports:
#
#   "r2"    — object storage the caller already has credentials for (Cloudflare
#             R2 in production). This module only forwards BLOB_*; it does not
#             provision the bucket, on the same grounds the GCP version never
#             provisioned PayFast credentials: a Cloudflare account is a human
#             decision, not infrastructure this Terraform owns.
#   "minio" — a MinIO container the app-stack module itself adds to the compose
#             file and fronts through Caddy, for an environment with no object
#             storage account of its own (staging).
variable "image_backend" {
  type = string
  validation {
    condition     = contains(["r2", "minio"], var.image_backend)
    error_message = "image_backend must be \"r2\" or \"minio\"."
  }
}

variable "blob_endpoint" {
  description = "Required when image_backend = \"r2\". Ignored for \"minio\", which always talks to the local minio service."
  type        = string
  default     = ""
}

variable "blob_bucket" {
  type    = string
  default = "gostore-images"
}

variable "blob_access_key_id" {
  type      = string
  default   = ""
  sensitive = true
}

variable "blob_secret_access_key" {
  type      = string
  default   = ""
  sensitive = true
}

variable "blob_region" {
  type    = string
  default = "auto"
}

variable "blob_public_base_url" {
  description = "Where a browser fetches images from. Required for \"r2\" (your R2 custom domain or pub-*.r2.dev address). Computed automatically for \"minio\" from images_domain."
  type        = string
  default     = ""
}

variable "images_domain" {
  description = "Only used when image_backend = \"minio\": the hostname Caddy fronts the MinIO bucket on, e.g. images-staging.example.com. Needs its own DNS record and certificate, separate from domain."
  type        = string
  default     = ""
}

variable "minio_root_password" {
  description = "Only used when image_backend = \"minio\". Generated by the caller with random_password."
  type        = string
  default     = ""
  sensitive   = true
}

variable "minio_data_mount" {
  type    = string
  default = "/mnt/gostore-data/minio"
}
