# Product images: a public bucket, reached through GCS's S3 interoperability API.
#
# Two things about this file are worth reading before changing it.
#
# The bucket is deliberately, wholly public. Images are served straight from it
# and never proxied through the store, which is what lets a CDN do the work — so
# `allUsers` gets `objectViewer` and that is not an oversight. It is also exactly
# why purchased files must never live here: public access is a bucket-level
# toggle, so a "private prefix" would not be private. The server refuses to boot
# if DOWNLOAD_BUCKET is ever set to this one.
#
# And the store reaches it over the **S3 interoperability API** rather than the
# native GCS one, because that is what minio-go speaks. The native API would mean
# adding the Google SDK to a binary whose dependency list is argued for line by
# line. That choice is why the HMAC key below exists at all: interoperability
# authenticates with an access key and a secret, not with the service account
# directly.

resource "google_storage_bucket" "images" {
  name     = "${var.app_name}-images-${var.project_id}"
  location = var.region

  # Uniform access, so permissions are the bucket policy below and nothing else.
  # Per-object ACLs would let one upload be public and the next one not, with no
  # way to see which from here.
  uniform_bucket_level_access = true

  # Photographs are not something Terraform should be able to delete on its way
  # past. A `terraform destroy` against an environment holding a real catalog's
  # images should fail and make somebody think, rather than succeed quietly.
  force_destroy = false
  lifecycle {
    prevent_destroy = true
  }

  # Replacing an image writes a new key and deletes the old object, so a bucket
  # that has been running for years accumulates nothing. Versioning is off for
  # the same reason: there is no edit-in-place to recover from.
  versioning {
    enabled = false
  }
}

resource "google_storage_bucket_iam_member" "images_public" {
  bucket = google_storage_bucket.images.name
  role   = "roles/storage.objectViewer"
  member = "allUsers"
}

# The runtime service account writes here; the world reads.
resource "google_storage_bucket_iam_member" "images_writer" {
  bucket = google_storage_bucket.images.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${google_service_account.run.email}"
}

# The interoperability credential. Terraform owns it, so rotating is a taint and
# an apply rather than a click in the console followed by wondering why uploads
# stopped.
resource "google_storage_hmac_key" "images" {
  service_account_email = google_service_account.run.email
}

resource "google_secret_manager_secret" "blob_secret_access_key" {
  secret_id = "${var.app_name}-blob-secret-access-key"
  replication {
    auto {}
  }
}

# Unlike the other secrets in secrets.tf, this one has a version written by
# Terraform: the value is generated by the resource above rather than by a human
# decision, so leaving it to be pasted in by hand would be inventing a manual
# step for a value nobody chooses.
resource "google_secret_manager_secret_version" "blob_secret_access_key" {
  secret      = google_secret_manager_secret.blob_secret_access_key.id
  secret_data = google_storage_hmac_key.images.secret
}
