terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 5.25"
    }
  }
}

# A remotely-managed tunnel: config_src = "cloudflare" puts the ingress rules
# in Cloudflare's API, where the resource below writes them and the connector
# pulls them down. The alternative, "local", expects a config.yml on the box
# and ignores anything set through the API — which would put the routing back
# in a file nobody reviews.
#
# tunnel_secret is deliberately not set. It is only needed for the
# credentials-file style of connector; a token-run connector gets everything
# it needs from the token read below.
resource "cloudflare_zero_trust_tunnel_cloudflared" "main" {
  account_id = var.account_id
  name       = var.name
  config_src = "cloudflare"
}

# The connector token, which is what `cloudflared tunnel run` authenticates
# with. It is a data source rather than an attribute of the resource above —
# the v5 provider does not expose one — and it is generated by Cloudflare
# rather than chosen by anybody, which is why nothing here asks a human for it.
data "cloudflare_zero_trust_tunnel_cloudflared_token" "main" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.main.id
}

resource "cloudflare_zero_trust_tunnel_cloudflared_config" "main" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.main.id

  config = {
    ingress = concat(
      [for r in var.routes : {
        hostname = r.hostname
        service  = r.service
      }],
      # Required last rule, and it must have no hostname: it is what answers a
      # request that matched nothing above. 404 rather than a service, so a
      # hostname pointed here by mistake says so instead of quietly reaching
      # the store.
      [{ service = "http_status:404" }],
    )
  }
}

# One CNAME per hostname, all pointing at the tunnel.
#
# Two values here are not preferences. proxied must be true, because
# *.cfargotunnel.com does not resolve publicly and only the orange-cloud path
# reaches a tunnel at all; and ttl must be 1 ("automatic"), because the API
# refuses any other TTL on a proxied record.
resource "cloudflare_dns_record" "route" {
  for_each = { for r in var.routes : r.hostname => r }

  zone_id = var.zone_id
  name    = each.value.hostname
  type    = "CNAME"
  content = "${cloudflare_zero_trust_tunnel_cloudflared.main.id}.cfargotunnel.com"
  proxied = true
  ttl     = 1
  comment = "gostore ${var.name} — managed by Terraform"
}
